language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-gulp-angular-subtask' ]; then cd .. && eval "mv $currentfolder generator-gulp-angular-subtask" && cd generator-gulp-angular-subtask; fi

